In [8]:
import numpy as np 
np.zeros((3,3))



array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [9]:
import numpy as np 
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [18]:

np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [14]:

m=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(m)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [27]:
a=2
b=3
a+b*a/b**2*np.sqrt(a)

np.float64(2.9428090415820636)

In [28]:
marks=np.array([50,60,70])
marks+5

array([55, 65, 75])

In [44]:
A=np.array([[1,2,3],[4,5,6],[7,8,9]])
B=np.array([[7,8,9],[10,11,12],[13,14,15]])
A@B.T

array([[ 50,  68,  86],
       [122, 167, 212],
       [194, 266, 338]])

In [45]:
arr=np.array([1,2,3,4,5])
np.mean(arr)

np.float64(3.0)

In [46]:
np.median(arr)

np.float64(3.0)

In [47]:
np.std(arr)

np.float64(1.4142135623730951)

In [48]:
np.var(arr)

np.float64(2.0)

In [15]:
m[1,1]

np.int64(5)

In [16]:
m[:,1]

array([2, 5, 8])